services:
  web-server:
    build:
      context: .
      dockerfile: dockerfile
    image: hasil_test_web_saucedemo_comv2 # Menentukan nama image secara spesifik
    ports:
      - "9434:80" # Port host 8080 ke port container 80
    container_name: hasil_test_web_saucedemo_comv2 # Nama container 
